spring:
  datasource:
    url: jdbc:mysql://localhost:3306/background_system?serverTimezone=UTC
    username: root
    password: xuexi123.

    druid:
      aop-patterns: com.yillint.admin.* #监控SpringBean
      filters: stat,wall,slf4j           #底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet:  #配置监控页功能
        enabled: true
        login-username: admin
        login-password: xuexi123.
        reset-enable: false

      web-stat-filter:  #监控Web
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter:
        stat: #对上面的filters的stat的详细配置
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    type: com.zaxxer.hikari.HikariDataSource

  jdbc:
    template:
      query-timeout: 3


#配置mybatis规则
mybatis:
  #config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true